openapi: 3.0.3
info:
  title: Echo Service - Python REST API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /health:
    get:
      operationId: checkHealth
      responses:
        "200":
          description: Health check successful!
  /:
    post:
      operationId: postEchoMessage
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad Request
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorPayload"
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
